{
  _futureTask.run();
  final Exception exception=new Exception();
  Future<Object> future=new FutureConverter(_futureTask){
    @Override protected Object convert(    Object v) throws Exception {
      throw exception;
    }
  }
;
  try {
    future.get();
    Assert.fail();
  }
 catch (  ExecutionException ee) {
    Assert.assertSame(exception,ee.getCause());
  }
  try {
    future.get(1,TimeUnit.SECONDS);
    Assert.fail();
  }
 catch (  ExecutionException ee) {
    Assert.assertSame(exception,ee.getCause());
  }
}
