{
  try {
    return _method.invoke(object,_arguments);
  }
 catch (  InvocationTargetException ite) {
    Throwable t=ite.getCause();
    if (t instanceof Exception) {
      throw (Exception)t;
    }
 else {
      throw new Exception(t);
    }
  }
}
