{
  try {
    addTrackback(req,res);
  }
 catch (  Exception e) {
    sendError(res,"An unknown error has occurred.");
    _log.error(e);
  }
  setForward(req,ActionConstants.COMMON_NULL);
}
